language: ruby
notifications:
  email:
    - ivanzotov@gmail.com
before_script:
  - "rake app:railties:install:migrations"
  - "rake app:db:migrate"
script: bundle exec rake spec

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode

rvm:
  - 2.0.0
  - 1.9.3
  - rbx-19mode
  - jruby-19mode