language: ruby
before_script:
  - "rake app:constructor_core:install:migrations"
  - "rake app:constructor_pages:install:migrations"
  - "rake app:db:migrate"
script:
  - "rspec ."
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode